Repository challenge-team-kotlin/camp-daddy, pull requests merged in 2024-03, with the labels that each got.

#28 ♻️ Refactor: BaseEntity lateinit 키워드 탈거 리팩토링 적용
  src/main/kotlin/com/challengeteamkotlin/campdaddy/common/entity/BaseTimeEntity.kt
Labels: ♻️Refactor

#30 🐛 Bugfix: CI .env 파일 생성 버그 파악 및 해결
  .github/workflows/camp-daddy-ci.yml
  src/test/resources/application.yml
Labels: 🐛 Bugfix

#31 ✅ Test: 채팅방 & 채팅 메시지 Entity 단위 테스트코드 추가
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/model/chat/ChatMessageEntity.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/model/chat/ChatRoomEntity.kt
  src/test/kotlin/com/challengeteamkotlin/campdaddy/domain/model/chat/ChatMessageTest.kt
  src/test/kotlin/com/challengeteamkotlin/campdaddy/domain/model/chat/ChatRoomTest.kt
  src/test/kotlin/com/challengeteamkotlin/campdaddy/fixture/chat/ChatMessageFixture.kt
  src/test/kotlin/com/challengeteamkotlin/campdaddy/fixture/chat/ChatRoomFixture.kt
  src/test/kotlin/com/challengeteamkotlin/campdaddy/fixture/member/MemberFixture.kt
  src/test/kotlin/com/challengeteamkotlin/campdaddy/fixture/product/ProductFixture.kt
  src/test/kotlin/com/challengeteamkotlin/campdaddy/fixture/reservation/ReservationFixture.kt
  src/test/kotlin/com/challengeteamkotlin/campdaddy/fixture/review/ReviewFixture.kt
Labels: ✅Test

#34 ⚙️ Add: .gitignore 파일 .env 추가
  .gitignore
Labels: ⚙️Add

#32 ✅ Test : 회원 Entity 단위 테스트코드 추가
  src/test/kotlin/com/challengeteamkotlin/campdaddy/domain/model/member/MemberEntityTest.kt
  src/test/kotlin/com/challengeteamkotlin/campdaddy/domain/model/member/RegionEntityTest.kt
  src/test/kotlin/com/challengeteamkotlin/campdaddy/domain/model/member/SidoAreaEntityTest.kt
  src/test/kotlin/com/challengeteamkotlin/campdaddy/domain/model/member/SiggAreaEntityTest.kt
  src/test/kotlin/com/challengeteamkotlin/campdaddy/fixture/member/MemberEntityFixture.kt
  src/test/kotlin/com/challengeteamkotlin/campdaddy/fixture/region/RegionFixture.kt
  src/test/kotlin/com/challengeteamkotlin/campdaddy/fixture/sido/SidoFixture.kt
  src/test/kotlin/com/challengeteamkotlin/campdaddy/fixture/sigg/SiggFixture.kt
Labels: ✅Test

#38 ✅ Test: 채팅 Entity 단위 테스트코드 수정
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/model/chat/ChatRoomEntity.kt
  src/test/kotlin/com/challengeteamkotlin/campdaddy/domain/model/chat/ChatRoomTest.kt
Labels: ✅Test

#36 ✅ Test: 예약 Entity 단위 테스트코드 추가
  src/test/kotlin/com/challengeteamkotlin/campdaddy/domain/model/reservation/ReservationEntityTest.kt
  src/test/kotlin/com/challengeteamkotlin/campdaddy/fixture/reservation/DateTimeFixture.kt
  src/test/kotlin/com/challengeteamkotlin/campdaddy/fixture/reservation/ReservationFixture.kt
Labels: ✅Test

#39 ⚙️ Add: 신규 테이블을 위한 엔티티 변경 및 추가, 신규 패키지 추가.
  src/main/kotlin/com/challengeteamkotlin/campdaddy/application/sample/SampleService.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/model/member/MemberEntity.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/model/product/LikeEntity.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/model/product/ProductEntity.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/model/product/ProductImageEntity.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/model/review/ReviewEntity.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/model/review/ReviewImageEntity.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/model/sample/SampleEntity.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/repository/sample/SampleRepository.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/infrastructure/hibernate/.gitkeep
  src/main/kotlin/com/challengeteamkotlin/campdaddy/infrastructure/hibernate/chat/.gitkeep
  src/main/kotlin/com/challengeteamkotlin/campdaddy/infrastructure/hibernate/member/.gitkeep
  src/main/kotlin/com/challengeteamkotlin/campdaddy/infrastructure/hibernate/product/.gitkeep
  src/main/kotlin/com/challengeteamkotlin/campdaddy/infrastructure/hibernate/reservation/.gitkeep
  src/main/kotlin/com/challengeteamkotlin/campdaddy/infrastructure/hibernate/review/.gitkeep
  src/main/kotlin/com/challengeteamkotlin/campdaddy/infrastructure/hibernate/sample/SampleJpaRepository.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/presentation/sample/SampleController.kt
Labels: ⚙️Add

#44 🐛 Bugfix: Sample코드 삭제
  src/main/kotlin/com/challengeteamkotlin/campdaddy/application/sample/SampleService.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/model/sample/SampleEntity.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/repository/sample/SampleRepository.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/infrastructure/hibernate/sample/SampleJpaRepository.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/presentation/sample/SampleController.kt
Labels: 🐛 Bugfix

#42 ✅ Test: 상품 Entity 단위 테스트코드 추가
  src/test/kotlin/com/challengeteamkotlin/campdaddy/domain/model/product/LikeEntityTest.kt
  src/test/kotlin/com/challengeteamkotlin/campdaddy/domain/model/product/ProductEntityTest.kt
  src/test/kotlin/com/challengeteamkotlin/campdaddy/fixture/product/LikeFixture.kt
  src/test/kotlin/com/challengeteamkotlin/campdaddy/fixture/product/ProductFixture.kt
  src/test/kotlin/com/challengeteamkotlin/campdaddy/fixture/product/ProductImageFixture.kt
Labels: ✅Test

#41 ✅ Test: 리뷰 엔티티 단위 테스트코드 조건 추가
  src/test/kotlin/com/challengeteamkotlin/campdaddy/domain/model/review/ReviewEntityTest.kt
  src/test/kotlin/com/challengeteamkotlin/campdaddy/domain/model/review/ReviewImageEntityTest.kt
  src/test/kotlin/com/challengeteamkotlin/campdaddy/fixture/review/ReviewFixture.kt
  src/test/kotlin/com/challengeteamkotlin/campdaddy/fixture/review/ReviewImageFixture.kt
Labels: ✅Test

#49 ⚙️ Add: 도메인 별 Repository 파일 추가
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/model/chat/ChatMessageEntity.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/model/chat/ChatRoomEntity.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/model/member/RegionEntity.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/model/member/SiggAreaEntity.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/model/product/LikeEntity.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/model/product/ProductEntity.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/model/product/ProductImageEntity.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/model/reservation/ReservationEntity.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/model/reservation/ReservationStatus.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/model/review/ReviewEntity.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/model/review/ReviewImageEntity.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/repository/.gitkeep
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/repository/chat/.gitkeep
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/repository/chat/ChatRoomRepository.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/repository/member/.gitkeep
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/repository/member/MemberRepository.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/repository/member/RegionRepository.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/repository/member/SidoAreaRepository.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/repository/member/SiggAreaRepository.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/repository/product/.gitkeep
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/repository/product/LikeRepository.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/repository/product/ProductImageRepository.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/repository/product/ProductRepository.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/repository/reservation/.gitkeep
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/repository/reservation/ReservationRepository.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/repository/review/.gitkeep
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/repository/review/ReviewRepository.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/infrastructure/hibernate/.gitkeep
  src/main/kotlin/com/challengeteamkotlin/campdaddy/infrastructure/hibernate/chat/.gitkeep
  src/main/kotlin/com/challengeteamkotlin/campdaddy/infrastructure/hibernate/chat/ChatRoomJpaRepository.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/infrastructure/hibernate/member/.gitkeep
  src/main/kotlin/com/challengeteamkotlin/campdaddy/infrastructure/hibernate/member/MemberJpaRepository.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/infrastructure/hibernate/member/RegionJpaRepository.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/infrastructure/hibernate/member/SidoAreaJpaRepository.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/infrastructure/hibernate/member/SiggAreaJpaRepository.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/infrastructure/hibernate/product/.gitkeep
  src/main/kotlin/com/challengeteamkotlin/campdaddy/infrastructure/hibernate/product/LikeJpaRepository.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/infrastructure/hibernate/product/ProductImageJpaRepository.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/infrastructure/hibernate/product/ProductJpaRepository.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/infrastructure/hibernate/reservation/.gitkeep
  src/main/kotlin/com/challengeteamkotlin/campdaddy/infrastructure/hibernate/reservation/ReservationJpaRepository.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/infrastructure/hibernate/review/.gitkeep
  src/main/kotlin/com/challengeteamkotlin/campdaddy/infrastructure/hibernate/review/ReviewJpaRepository.kt
  src/test/kotlin/com/challengeteamkotlin/campdaddy/domain/model/chat/ChatMessageTest.kt
  src/test/kotlin/com/challengeteamkotlin/campdaddy/domain/model/chat/ChatRoomTest.kt
  src/test/kotlin/com/challengeteamkotlin/campdaddy/domain/model/member/RegionEntityTest.kt
  src/test/kotlin/com/challengeteamkotlin/campdaddy/domain/model/member/SiggAreaEntityTest.kt
  src/test/kotlin/com/challengeteamkotlin/campdaddy/domain/model/product/LikeEntityTest.kt
  src/test/kotlin/com/challengeteamkotlin/campdaddy/domain/model/product/ProductEntityTest.kt
  src/test/kotlin/com/challengeteamkotlin/campdaddy/fixture/reservation/ReservationFixture.kt
Labels: ⚙️Add

#47 ✨ Feat: 채팅 메세지 CRUD 기능 추가
  build.gradle.kts
  src/main/kotlin/com/challengeteamkotlin/campdaddy/application/chat/.gitkeep
  src/main/kotlin/com/challengeteamkotlin/campdaddy/application/chat/ChatMessageService.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/common/config/chat/StompWebSocketConfig.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/common/config/chat/handler/ClientMessageInterceptor.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/model/chat/ChatMessageEntity.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/model/chat/MessageStatus.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/repository/chat/ChatMessageRepository.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/infrastructure/hibernate/chat/ChatMessageJpaRepository.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/presentation/chat/.gitkeep
  src/main/kotlin/com/challengeteamkotlin/campdaddy/presentation/chat/ChatMessageController.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/presentation/chat/dto/request/MessageRequest.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/presentation/chat/dto/response/MessageResponse.kt
Labels: ✨Feature

#53 ✨ Feat: 채팅방 CRUD 기능 추가
  src/main/kotlin/com/challengeteamkotlin/campdaddy/application/chat/ChatRoomService.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/application/chat/exception/ChatErrorCode.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/model/chat/ChatRoomEntity.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/infrastructure/hibernate/chat/ChatMessageJpaRepository.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/infrastructure/hibernate/chat/ChatRoomJpaRepository.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/presentation/chat/ChatRoomController.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/presentation/chat/dto/request/CreateChatRoomRequest.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/presentation/chat/dto/response/ChatRoomDetailResponse.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/presentation/chat/dto/response/ChatRoomResponse.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/presentation/product/dto/response/ProductDetailResponse.kt
  src/test/kotlin/com/challengeteamkotlin/campdaddy/domain/model/chat/ChatMessageTest.kt
  src/test/kotlin/com/challengeteamkotlin/campdaddy/domain/model/chat/ChatRoomTest.kt
  src/test/kotlin/com/challengeteamkotlin/campdaddy/fixture/chat/ChatRoomFixture.kt
Labels: ✨Feature

#56 ✨ Feat: 예약 CRUD 기능 추가
  src/main/kotlin/com/challengeteamkotlin/campdaddy/application/reservation/.gitkeep
  src/main/kotlin/com/challengeteamkotlin/campdaddy/application/reservation/ReservationService.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/application/reservation/exception/AlreadyReservedDateException.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/application/reservation/exception/EndDateLessThanStartDateException.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/application/reservation/exception/ReservationErrorCode.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/model/reservation/ReservationEntity.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/infrastructure/hibernate/reservation/ReservationJpaRepository.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/presentation/reservation/.gitkeep
  src/main/kotlin/com/challengeteamkotlin/campdaddy/presentation/reservation/ReservationController.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/presentation/reservation/dto/reqeust/CreateReservationRequest.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/presentation/reservation/dto/reqeust/PatchReservationStatusRequest.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/presentation/reservation/dto/response/ReservationResponse.kt
  src/test/kotlin/com/challengeteamkotlin/campdaddy/fixture/reservation/DateTimeFixture.kt
  src/test/kotlin/com/challengeteamkotlin/campdaddy/fixture/reservation/ReservationFixture.kt
Labels: ✨Feature

#55 ✨ Feat : 회원 CRUD & security, oauth2 kakao 로그인 기능 추가
  build.gradle.kts
  src/main/kotlin/com/challengeteamkotlin/campdaddy/application/auth/KakaoOAuth2LoginService.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/application/auth/SocialMemberService.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/application/member/.gitkeep
  src/main/kotlin/com/challengeteamkotlin/campdaddy/application/member/MemberService.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/application/member/exception/MemberErrorCode.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/application/member/exception/RetrievalFailureException.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/common/config/PropertiesConfig.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/common/exception/code/CommonErrorCode.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/common/security/SecurityConfig.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/common/security/UserPrincipal.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/model/member/MemberEntity.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/model/member/MemberProvider.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/repository/member/MemberRepository.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/infrastructure/client/config/RestClientConfig.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/infrastructure/client/kakao/KakaoOAuth2Client.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/infrastructure/client/properties/KakaoProviderProperties.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/infrastructure/client/properties/KakaoRegistrationProperties.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/infrastructure/hibernate/member/MemberJpaRepository.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/infrastructure/jwt/JwtAuthenticationFilter.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/infrastructure/jwt/JwtAuthenticationToken.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/infrastructure/jwt/JwtPlugin.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/infrastructure/jwt/JwtProperties.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/presentation/auth/KakaoOAuth2LoginController.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/presentation/auth/dto/response/KakaoTokenResponse.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/presentation/auth/dto/response/KakaoUserAccountResponse.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/presentation/auth/dto/response/KakaoUserInfoResponse.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/presentation/auth/dto/response/KakaoUserPropertiesResponse.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/presentation/member/.gitkeep
  src/main/kotlin/com/challengeteamkotlin/campdaddy/presentation/member/MemberController.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/presentation/member/dto/request/UpdateProfileRequest.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/presentation/member/dto/response/LoginResponse.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/presentation/member/dto/response/MemberResponse.kt
  src/main/resources/application.yml
  src/test/kotlin/com/challengeteamkotlin/campdaddy/domain/model/member/MemberEntityTest.kt
  src/test/kotlin/com/challengeteamkotlin/campdaddy/fixture/member/MemberEntityFixture.kt
  src/test/kotlin/com/challengeteamkotlin/campdaddy/fixture/member/MemberFixture.kt
  src/test/resources/application.yml
Labels: ✨Feature

#61 ♻️ Refactor: 채팅 도메인 기능 리팩토링 적용
  src/main/kotlin/com/challengeteamkotlin/campdaddy/application/chat/ChatMessageService.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/application/chat/exception/ChatErrorCode.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/application/chat/exception/ChatFailureException.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/presentation/chat/ChatMessageController.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/presentation/chat/ChatRoomController.kt
Labels: ♻️Refactor

#65 ✅ Test: 채팅 메세지, 채팅방 Service 단위 테스트코드 추가
  src/test/kotlin/com/challengeteamkotlin/campdaddy/application/chat/ChatMessageServiceTest.kt
  src/test/kotlin/com/challengeteamkotlin/campdaddy/application/chat/ChatRoomServiceTest.kt
  src/test/kotlin/com/challengeteamkotlin/campdaddy/domain/model/member/MemberEntityTest.kt
  src/test/kotlin/com/challengeteamkotlin/campdaddy/fixture/chat/ChatMessageFixture.kt
  src/test/kotlin/com/challengeteamkotlin/campdaddy/fixture/chat/ChatRoomFixture.kt
  src/test/kotlin/com/challengeteamkotlin/campdaddy/fixture/member/MemberEntityFixture.kt
  src/test/kotlin/com/challengeteamkotlin/campdaddy/fixture/member/MemberFixture.kt
  src/test/kotlin/com/challengeteamkotlin/campdaddy/fixture/product/ProductFixture.kt
Labels: ✅Test

#70 ♻️ Refactor: Entity id val -> var 리팩토링 적용
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/model/chat/ChatMessageEntity.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/model/chat/ChatRoomEntity.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/model/member/MemberEntity.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/model/member/RegionEntity.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/model/member/SidoAreaEntity.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/model/member/SiggAreaEntity.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/model/product/LikeEntity.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/model/product/ProductEntity.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/model/product/ProductImageEntity.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/model/reservation/ReservationEntity.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/model/review/ReviewEntity.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/model/review/ReviewImageEntity.kt
Labels: ♻️Refactor

#64 ✅ Test: 회원 서비스 테스트코드 추가
  build.gradle.kts
  src/main/kotlin/com/challengeteamkotlin/campdaddy/application/auth/exception/AuthErrorCode.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/application/chat/ChatMessageService.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/application/member/MemberService.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/application/member/exception/AccessDeniedException.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/application/member/exception/MemberErrorCode.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/application/review/ReviewService.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/common/exception/code/CommonErrorCode.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/infrastructure/client/kakao/KakaoOAuth2Client.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/infrastructure/hibernate/member/MemberJpaRepository.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/presentation/member/MemberController.kt
  src/test/kotlin/com/challengeteamkotlin/campdaddy/application/auth/KakaoOAuth2LoginServiceTest.kt
  src/test/kotlin/com/challengeteamkotlin/campdaddy/application/auth/SocialMemberServiceTest.kt
  src/test/kotlin/com/challengeteamkotlin/campdaddy/application/member/MemberServiceTest.kt
  src/test/kotlin/com/challengeteamkotlin/campdaddy/domain/model/member/MemberEntityTest.kt
  src/test/kotlin/com/challengeteamkotlin/campdaddy/fixture/auth/AuthFixture.kt
  src/test/kotlin/com/challengeteamkotlin/campdaddy/fixture/member/MemberEntityFixture.kt
  src/test/kotlin/com/challengeteamkotlin/campdaddy/infrastructure/client/kakao/KakaoOAuth2ClientTest.kt
Labels: ✅Test

#77 🐛 Bugfix: CD Docker Container 실행 버그 파악 및 해결
  .github/workflows/camp-daddy-cd.yml
  Dockerfile
Labels: 🐛 Bugfix

#79 ✅ Test: 리뷰 서비스 테스트 코드 추가
  src/main/kotlin/com/challengeteamkotlin/campdaddy/application/review/ReviewService.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/application/review/execption/ReviewErrorCode.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/presentation/review/ReviewController.kt
  src/test/kotlin/com/challengeteamkotlin/campdaddy/application/review/ReviewServiceTest.kt
Labels: ✅Test

#82 ✨ Feat: 예약 CRUD 추가 개발
  src/main/kotlin/com/challengeteamkotlin/campdaddy/application/reservation/ReservationService.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/application/reservation/exception/InvalidReservationPatchRequest.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/application/reservation/exception/ReservationErrorCode.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/application/reservation/handler/PatchReservationHandler.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/infrastructure/hibernate/reservation/ReservationJpaRepository.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/presentation/reservation/ReservationController.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/presentation/reservation/dto/reqeust/CreateReservationRequest.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/presentation/reservation/dto/reqeust/PatchReservationStatusRequest.kt
  src/test/kotlin/com/challengeteamkotlin/campdaddy/application/reservation/ReservationServiceTest.kt
  src/test/kotlin/com/challengeteamkotlin/campdaddy/fixture/reservation/DateFixture.kt
  src/test/kotlin/com/challengeteamkotlin/campdaddy/fixture/reservation/ReservationFixture.kt
Labels: ✨Feature

#86 ♻️ Refactor: Chat 도메인 Repository DIP 리팩토링 적용
  src/main/kotlin/com/challengeteamkotlin/campdaddy/application/chat/ChatMessageService.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/application/chat/ChatRoomService.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/repository/chat/ChatMessageRepository.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/repository/chat/ChatMessageRepositoryImpl.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/repository/chat/ChatRoomRepository.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/repository/chat/ChatRoomRepositoryImpl.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/infrastructure/hibernate/chat/ChatMessageJpaRepository.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/presentation/chat/ChatRoomController.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/presentation/chat/context/repository/ChatConfig.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/presentation/chat/dto/response/ChatRoomResponse.kt
  src/test/kotlin/com/challengeteamkotlin/campdaddy/application/chat/ChatMessageServiceTest.kt
  src/test/kotlin/com/challengeteamkotlin/campdaddy/application/chat/ChatRoomServiceTest.kt
  src/test/kotlin/com/challengeteamkotlin/campdaddy/fixture/chat/ChatMessageFixture.kt
Labels: ♻️Refactor

#93 ♻️ Refactor: Reservation 도메인 Repository DIP 리팩토링 적용
  src/main/kotlin/com/challengeteamkotlin/campdaddy/application/reservation/ReservationService.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/application/review/ReviewService.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/repository/reservation/ReservationRepository.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/infrastructure/hibernate/reservation/ReservationRepositoryImpl.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/presentation/reservation/context/repository/ReservationConfig.kt
  src/test/kotlin/com/challengeteamkotlin/campdaddy/application/reservation/ReservationServiceTest.kt
  src/test/kotlin/com/challengeteamkotlin/campdaddy/application/review/ReviewServiceTest.kt
Labels: ♻️Refactor

#95 ♻️ Refactor: Review 도메인 Repository DIP 리팩토링 적용
  src/main/kotlin/com/challengeteamkotlin/campdaddy/application/review/ReviewService.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/repository/review/ReviewRepository.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/infrastructure/hibernate/review/ReviewRepositoryImpl.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/presentation/review/context/repository/ReviewConfig.kt
  src/test/kotlin/com/challengeteamkotlin/campdaddy/application/review/ReviewServiceTest.kt
Labels: ♻️Refactor

#105 ♻️ Refactor: DataBase RDS로 전환 리팩토링 적용
  build.gradle.kts
  src/main/resources/application.yml
  src/test/resources/application.yml
Labels: ♻️Refactor

#103 🐛 Bugfix: ChatRoomEntity 연관관계 ID Insert 버그 파악 및 해결
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/model/chat/ChatRoomEntity.kt
Labels: 🐛 Bugfix

#99 ♻️ Refactor: Product 도메인 Repository DIP 리팩토링 적용
  src/main/kotlin/com/challengeteamkotlin/campdaddy/application/chat/ChatRoomService.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/application/product/ProductService.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/application/reservation/ReservationService.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/application/review/ReviewService.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/model/product/ProductEntity.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/repository/product/ProductRepository.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/repository/product/ProductRepositoryImpl.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/infrastructure/hibernate/product/ProductJpaRepository.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/presentation/chat/dto/response/ChatRoomResponse.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/presentation/product/context/repository/ProductConfig.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/presentation/product/dto/response/SearchProductResponse.kt
  src/test/kotlin/com/challengeteamkotlin/campdaddy/application/reservation/ReservationServiceTest.kt
  src/test/kotlin/com/challengeteamkotlin/campdaddy/application/review/ReviewServiceTest.kt
Labels: ♻️Refactor

#107 🐛 Bugfix: member 버그 파악 및 해결
  src/main/kotlin/com/challengeteamkotlin/campdaddy/application/auth/OAuth2UserService.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/common/security/SecurityConfig.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/model/member/MemberEntity.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/presentation/auth/dto/response/OAuth2UserInfo.kt
  src/main/resources/application.yml
Labels: 🐛 Bugfix

#106 🐛 Bugfix: Product 버그 수정
  src/main/kotlin/com/challengeteamkotlin/campdaddy/application/product/ProductService.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/model/product/ProductEntity.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/presentation/product/dto/response/GetProductByMemberResponse.kt
  src/main/resources/application.yml
  src/test/resources/application.yml
Labels: 🐛 Bugfix

#111 🐛 Bugfix: 채팅방 > 채팅 메세지 > 닉네임 조회 시 LazyInitializationException 버그 파악 및 해결
  src/main/kotlin/com/challengeteamkotlin/campdaddy/application/chat/ChatRoomService.kt
Labels: 🐛 Bugfix

#113 🐛 Bugfix: 소셜 로그인 email 검증 로직 버그 파악 및 해결
  src/main/kotlin/com/challengeteamkotlin/campdaddy/application/auth/SocialMemberService.kt
  src/test/kotlin/com/challengeteamkotlin/campdaddy/application/auth/SocialMemberServiceTest.kt
Labels: 🐛 Bugfix

#114 🐛 Bugfix: 상품 이미지 소프트 삭제 적용.
  src/main/kotlin/com/challengeteamkotlin/campdaddy/application/auth/SocialMemberService.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/common/entity/BaseEntity.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/model/member/MemberEntity.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/model/product/ProductEntity.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/model/product/ProductImageEntity.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/model/reservation/ReservationEntity.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/model/review/ReviewEntity.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/model/review/ReviewImageEntity.kt
  src/main/resources/application.yml
Labels: 🐛 Bugfix

#116 ♻️Refactor: 회원 소셜 로그인 기능 리팩토링 적용
  src/main/kotlin/com/challengeteamkotlin/campdaddy/application/auth/OAuth2LoginSuccessHandler.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/application/auth/OAuth2UserService.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/application/auth/SocialMemberService.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/model/member/MemberEntity.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/presentation/auth/dto/OAuth2Controller.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/presentation/auth/dto/request/OAuth2SignupRequest.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/presentation/auth/dto/response/OAuth2UserInfo.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/presentation/auth/dto/response/SocialLoginResponse.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/presentation/member/dto/request/UpdateProfileRequest.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/presentation/member/dto/response/MemberResponse.kt
  src/test/kotlin/com/challengeteamkotlin/campdaddy/application/auth/SocialMemberServiceTest.kt
  src/test/kotlin/com/challengeteamkotlin/campdaddy/application/member/MemberServiceTest.kt
  src/test/kotlin/com/challengeteamkotlin/campdaddy/fixture/auth/AuthFixture.kt
  src/test/kotlin/com/challengeteamkotlin/campdaddy/fixture/member/MemberEntityFixture.kt
  src/test/kotlin/com/challengeteamkotlin/campdaddy/fixture/member/MemberFixture.kt
Labels: ♻️Refactor

#120 ✨ Feat: Reservation Event 처리 기능 추가
  build.gradle.kts
  src/main/kotlin/com/challengeteamkotlin/campdaddy/application/reservation/ReservationService.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/application/scheduler/SchedulerService.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/common/config/SchedulingConfig.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/event/reservation/ReservationEventPublisher.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/event/reservation/ReservationEventSubscriber.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/model/reservation/ReservationStatus.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/infrastructure/aws/SnsEventPublisher.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/infrastructure/aws/SqsEventSubscriber.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/infrastructure/aws/config/AwsEventConfig.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/infrastructure/event/reservation/ReservationEventPublisherImpl.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/infrastructure/event/reservation/ReservationEventSubscriberImpl.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/presentation/reservation/context/event/ReservationEventConfig.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/presentation/reservation/context/repository/ReservationRepositoryConfig.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/presentation/reservation/dto/event/ReservationEvent.kt
  src/main/resources/application.yml
  src/test/kotlin/com/challengeteamkotlin/campdaddy/application/reservation/ReservationServiceTest.kt
  src/test/resources/application.yml
Labels: ✨Feature

#118 ✨ Feat: jwt cookie 저장, 헤더에 던지기 기능 추가
  src/main/kotlin/com/challengeteamkotlin/campdaddy/application/auth/OAuth2LoginSuccessHandler.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/application/auth/SocialMemberService.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/infrastructure/jwt/JwtPlugin.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/presentation/auth/dto/OAuth2Controller.kt
Labels: ✨Feature

#124 ✨ Feat: Reservation Event 처리 채팅 연동 기능 추가
  src/main/kotlin/com/challengeteamkotlin/campdaddy/application/chat/ChatMessageSendManager.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/application/chat/ChatRoomService.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/application/scheduler/SchedulerService.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/model/chat/MessageStatus.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/presentation/chat/ChatMessageController.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/presentation/reservation/dto/event/ReservationEvent.kt
Labels: ✨Feature

#127 ✨ Feat: 예약 event groupId, 중복제거 Id 기능 추가
  src/main/kotlin/com/challengeteamkotlin/campdaddy/infrastructure/aws/SnsEventPublisher.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/infrastructure/event/reservation/ReservationEventPublisherImpl.kt
Labels: ✨Feature

#130 ⚙️ Add: yml 파일 리다이렉트 수정
  src/main/resources/application.yml
Labels: ⚙️Add

#132 ⚙️ Add: test 환경 applicaiton.yml 파일 리다이렉트 수정
  src/test/resources/application.yml
Labels: ⚙️Add

#133 ✨ Feat: 유저 인증/인가 메소드 추가
  src/main/kotlin/com/challengeteamkotlin/campdaddy/application/member/MemberService.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/common/auth/UserAuthorization.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/infrastructure/hibernate/member/MemberJpaRepository.kt
Labels: ✨Feature

#135 ⚙️ Add: swagger 코드 추가
  src/main/kotlin/com/challengeteamkotlin/campdaddy/infrastructure/swagger/config/SwaggerConfig.kt
Labels: ⚙️Add

#137 ⚙️ Add: swagger 서버 추가
  src/main/kotlin/com/challengeteamkotlin/campdaddy/infrastructure/swagger/config/SwaggerConfig.kt
Labels: ⚙️Add

#138 ♻️ Refactor: 채팅 도메인 인증 / 개인 채팅 조회 기능 리팩토링 적용
  src/main/kotlin/com/challengeteamkotlin/campdaddy/application/chat/ChatRoomService.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/common/auth/UserAuthorization.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/repository/chat/ChatRoomRepository.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/repository/chat/ChatRoomRepositoryImpl.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/infrastructure/hibernate/chat/ChatRoomQueryDslRepository.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/infrastructure/hibernate/chat/ChatRoomQueryDslRepositoryImpl.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/infrastructure/hibernate/querydsl/QueryDslSupport.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/presentation/chat/ChatRoomController.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/presentation/chat/context/repository/ChatConfig.kt
  src/test/kotlin/com/challengeteamkotlin/campdaddy/application/chat/ChatRoomServiceTest.kt
  src/test/kotlin/com/challengeteamkotlin/campdaddy/fixture/auth/AuthFixture.kt
Labels: ♻️Refactor

#140 🐛 Bugfix: jwt filter header bearer null 버그 파악 및 해결
  src/main/kotlin/com/challengeteamkotlin/campdaddy/infrastructure/jwt/JwtAuthenticationFilter.kt
Labels: 🐛 Bugfix

#142 ✨Feat: CORS 오류 해결 코드
  src/main/kotlin/com/challengeteamkotlin/campdaddy/common/security/SecurityConfig.kt
Labels: ✨Feature

#144 ✨ Feat: 최초 페이지 상품 조회 추가.
  src/main/kotlin/com/challengeteamkotlin/campdaddy/application/product/ProductService.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/repository/product/ProductRepository.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/repository/product/ProductRepositoryImpl.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/presentation/product/ProductController.kt
  src/main/resources/application.yml
Labels: ✨Feature
