Repository challenge-team-kotlin/camp-daddy, pull requests merged in 2024-02, with the labels that each got.

#2 📝 Docs: Issue 템플릿 & PR 템플릿 문서 추가
  .github/ISSUE_TEMPLATE/기능-추가-이슈-템플릿.md
  .github/ISSUE_TEMPLATE/리팩토링-적용-이슈-템플릿.md
  .github/ISSUE_TEMPLATE/문서-등록-이슈-템플릿.md
  .github/ISSUE_TEMPLATE/버그픽스-등록-이슈-템플릿.md
  .github/ISSUE_TEMPLATE/코드-또는-파일-삭제-이슈-템플릿.md
  .github/ISSUE_TEMPLATE/테스트코드-추가-이슈-템플릿.md
  .github/ISSUE_TEMPLATE/파일-추가-이슈-템플릿.md
  PULL_REQUEST_TEMPLATE.md
Labels: 📝Docs

#4 🐛 Bugfix: PULL_REQUEST.md 버그 파악 및 해결
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 🐛 Bugfix

#6 ⚙️ Add: MVP Entity 및 DDD 기반 패키지 구조화.
  src/main/kotlin/com/challengeteamkotlin/campdaddy/application/chat/.gitkeep
  src/main/kotlin/com/challengeteamkotlin/campdaddy/application/member/.gitkeep
  src/main/kotlin/com/challengeteamkotlin/campdaddy/application/product/.gitkeep
  src/main/kotlin/com/challengeteamkotlin/campdaddy/application/reservation/.gitkeep
  src/main/kotlin/com/challengeteamkotlin/campdaddy/application/review/.gitkeep
  src/main/kotlin/com/challengeteamkotlin/campdaddy/common/entity/BaseEntity.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/common/entity/BaseTimeEntity.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/model/chat/ChatMessageEntity.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/model/chat/ChatRoomEntity.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/model/member/MemberEntity.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/model/member/RegionEntity.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/model/member/SidoAreaEntity.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/model/member/SiggAreaEntity.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/model/product/Category.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/model/product/ProductEntity.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/model/reservation/ReservationEntity.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/model/reservation/ReservationsStatus.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/model/review/ReviewEntity.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/repository/chat/.gitkeep
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/repository/member/.gitkeep
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/repository/product/.gitkeep
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/repository/reservation/.gitkeep
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/repository/review/.gitkeep
  src/main/kotlin/com/challengeteamkotlin/campdaddy/presentation/chat/.gitkeep
  src/main/kotlin/com/challengeteamkotlin/campdaddy/presentation/member/.gitkeep
  src/main/kotlin/com/challengeteamkotlin/campdaddy/presentation/product/.gitkeep
  src/main/kotlin/com/challengeteamkotlin/campdaddy/presentation/reservation/.gitkeep
  src/main/kotlin/com/challengeteamkotlin/campdaddy/presentation/review/.gitkeep
Labels: ⚙️Add

#8 ⚙️ Add: build.gradle.kts 주석 추가
  build.gradle.kts
Labels: ⚙️Add

#16 🐛 Bugfix: 파일 추가 이슈 템플릿 버그 파악 및 해결
  .github/ISSUE_TEMPLATE/파일-추가-이슈-템플릿.md
Labels: 🐛 Bugfix

#17 ✨ Feat: 전역 예외 처리 기능 추가
  src/main/kotlin/com/challengeteamkotlin/campdaddy/common/exception/CustomException.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/common/exception/EntityNotFoundException.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/common/exception/advice/RestApiExceptionAdvice.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/common/exception/code/CommonErrorCode.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/common/exception/code/ErrorCode.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/common/exception/dto/response/ErrorResponse.kt
Labels: ✨Feature

#20 🐛 Bugfix: Entity 생성 버그 파악 및 해결
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/model/member/MemberEntity.kt
  src/main/kotlin/com/challengeteamkotlin/campdaddy/domain/model/product/ProductEntity.kt
Labels: 🐛 Bugfix

#18 ✨ Feat: 프로젝트 CI 기능 추가
  .github/workflows/camp-daddy-ci.yml
Labels: ✨Feature

#23 ⚙️ Add: application.yml 파일 수정
  build.gradle.kts
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: ⚙️Add

#26 ♻️ Refactor: CI 기능 리팩토링 적용
  .github/workflows/camp-daddy-ci.yml
Labels: ♻️Refactor
